CREATE TABLE `veiculos`(
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `tipo` VARCHAR(255) NOT NULL,
    `marca` VARCHAR(255) NOT NULL,
    `modelo` VARCHAR(255) NOT NULL,
    `ano` VARCHAR(255) NOT NULL,
    `cor` VARCHAR(255) NOT NULL,
    `placa` VARCHAR(255) NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)